const exerciseData = {
    abs: [
            {id: 1, name: 'Ab Rollouts'},
            {id: 2, name: 'Cable Crunches'},
            {id: 3, name: 'Decline Bench Crunches'},
            {id: 4, name: 'Hanging Leg Raises'},
            {id: 5, name: 'Machine Crunhces'},
            {id: 6, name: 'Roman Chair Leg Raises'},
            {id: 7, name: 'Russian Twists'},
            {id: 8, name: 'Seated Cable Twists'},
        ],
    back:[
            {id: 1, name: 'Barbell Row'},
            {id: 2, name: 'Barbell Shrug'},
            {id: 3, name: 'Chin up'},
            {id: 4, name: 'Deadlift'},
            {id: 5, name: 'Dumbbell Row'},
            {id: 6, name: 'Good Morning'},
            {id: 7, name: 'Hammer Strength Row'},
            {id: 8, name: 'Lat Pulldown'},
            {id: 9, name: 'Machine Shrug'},
            {id: 10, name: 'Neutral Chin Up'},
            {id: 11, name: 'Pendlay Row'},
            {id: 12, name:'Pull Up'},
            {id: 13, name:'Rack Pull'},
            {id: 14, name:'Seated Cable Row'},
            {id: 15, name:'Straight-Arm Cable Pushdown'},
            {id: 16, name:'T-Bar Row'},
        ],
    biceps:[
            {id: 1, name: 'Barbell Curl'},
            {id: 2, name: 'Cable Curl'},
            {id: 3, name: 'Concentration Curl'},
            {id: 4, name: 'Dumbbell Curl'},
            {id: 5, name: 'Hammer Curl'},
            {id: 6, name: 'Incline Dumbbell Curl'},
            {id: 7, name: 'Preacher Curl'},
            {id: 8, name: 'Seated Machine Curl'},
        ],
    cardio: [
            {id: 1, name: 'Cycling'},
            {id: 2, name: 'Elliptical Trainer'},
            {id: 3, name: 'High Intensity Interval Training (HIIT)'},
            {id: 4, name: 'Jump Rope'},
            {id: 5, name: 'Rowing Machine'},
            {id: 6, name: 'Running'},
            {id: 7, name: 'Swimming'},
            {id: 8, name: 'Walking'},
        ],
    chest:[
            {id: 1, name: 'Barbell Bench Press'},
            {id: 2, name: 'Cable Crossover'},
            {id: 3, name: 'Dumbbell Fly'},
            {id: 4, name: 'Incline Bench Press'},
            {id: 5, name: 'Pec Deck'},
            {id: 6, name: 'Push-Ups'},
            {id: 7, name: 'Seated Machine Fly'},
        ],
    legs:[
            {id: 1, name: 'Calf Raise'},
            {id: 2, name: 'Glute Bridge'},
            {id: 3, name: 'Lunge'},
            {id: 4, name: 'Leg Press'},
            {id: 5, name: 'Leg Raise'},
            {id: 6, name: 'Leg Extension'},
            {id: 7, name: 'Squat'},
            {id: 8, name: 'Step-Up'},
            {id: 9, name: 'Hip Abduction'},
            {id: 10, name: 'Leg Curl'},
        ],
    shoulders: [
            {id: 1, name: 'Arnold Dumbbell Press'},
            {id: 2, name: 'Behind The Neck Barbell Press'},
            {id: 3, name: 'Cable Face Pull'},
            {id: 4, name: 'Lateral Dumbbell Raise'},
            {id: 5, name: 'Lateral Machine Raise'},
            {id: 6, name: 'Log Press'},
            {id: 7, name: 'Overhead Press'},
            {id: 8, name: 'Push Press'},
            {id: 9, name: 'Rear Delt Dumbbell Raise'},
        ],
    triceps: [
            {id: 1, name: 'Cable Overhead Triceps Extension'},
            {id: 2, name: 'Close Grip Barbell Bench Press'},
            {id: 3, name: 'Dumbbell Overhead Triceps Extension'},
            {id: 4, name: 'Lying Triceps Extension'},
            {id: 5, name: 'Machine Dip'},
            {id: 6, name: 'Dip'},
            {id: 7, name: 'Push Down'},
            {id: 10, name: 'Skull Crusher'}
        ],
};
export default exerciseData;